#==============================================================================
# vim: softtabstop=2 shiftwidth=2 expandtab fenc=utf-8 cc=81 tw=80
#==============================================================================
#
# DESCRIPTION: Build a debian image for docker with docker
#
#==============================================================================

---
# Loads some helpful aliases
aliases: defaults.yaml
# Enables qcow2 checkpoint
# checkpoint: docker.yaml
#== Global variables use by Kameleon engine and the steps
global:
  ## User varibales : used by the recipe
  user_name: kameleon
  user_password: $$user_name

  # Distribution
  distrib: debian
  release: wheezy
  arch: amd64

  ## Docker options
  docker_dns: 208.67.222.222
  docker_image: $$kameleon_recipe_name
  docker_hostname: $$kameleon_recipe_name

  # rootfs options
  rootfs: $$kameleon_cwd/rootfs

  ## System variables. Required by kameleon engine
  # Include specific steps
  include_steps:
    - $$distrib/$$release
    - $$distrib

  # Apt options
  apt_repository: http://ftp.debian.org/debian/
  apt_enable_contrib: true
  apt_enable_nonfree: true

  # Shell session from where we launch exec_out commands. There is often a
  # local bash session, but it can be a remote shell on other machines or on
  # any shell. (eg. bash, chroot, fakechroot, ssh, tmux, lxc...)
  out_context:
    cmd: bash
    workdir: $$kameleon_cwd
    proxy_cache: localhost

  # Shell session that allows us to connect to the building machine in order to
  # configure it and setup additional programs
  ssh_config_file: $$kameleon_cwd/ssh_config
  in_context:
    cmd: LC_ALL=POSIX ssh -F $$ssh_config_file $$kameleon_recipe_name -t /bin/bash
    workdir: /root/kameleon_workdir
    proxy_cache: 172.17.42.1

#== Bootstrap the new system and create the 'in_context'
bootstrap:
  - debootstrap:
    - include_pkg: >
        ifupdown locales libui-dialog-perl dialog isc-dhcp-client netbase
        net-tools iproute acpid openssh-server pciutils extlinux
        linux-image-$$arch
    - release: $$release
    - arch: $$arch
    - repository: $$apt_repository
    - variant: minbase
  - prepare_docker
  - start_docker


#== Install and configuration steps
# WARNING: this part should be independante from the out context (whenever
# possible...)
setup:
  # Install
  - configure_apt:
    - repository: $$apt_repository
    - enable_contrib_repo: $$apt_enable_contrib
    - enable_nonfree_repo: $$apt_enable_nonfree
  - upgrade_system:
    - dist_upgrade: true
  - install_software:
    - packages: >
        debian-keyring ntp rsync sudo less vim bash-completion
  # Configuration
  - configure_system:
    - locales: POSIX C en_US fr_FR de_DE
    - lang: en_US.UTF-8
    - timezone: UTC
  - configure_keyboard:
    - layout: "us,fr,de"
  - create_group:
    - name: admin
  - create_user:
    - name: $$user_name
    - groups: sudo admin
    - password: $$user_password

#== Export the generated appliance in the format of your choice
export:
  - save_docker_appliance:
    - commit:
      - exec_out: docker commit $(cat MAIN_CONTAINER_ID) $$kameleon_recipe_name:latest
